### ISSUE TITLE
Error "Cannot read property 'map' of undefined" appears after clicking on "Select a device" with Android target

### ISSUE THREAD

**Issue by JaneySprings** [Clancey/vscode-comet#16]
OS: MacOS 12.1
VSCode: 1.64.2
Plugin: Comet for .NET Mobile v0.3.15
Android Studio: Bumblebee 2021.1.1 Patch 1
Dotnet SDK: 6.0.200

iOS works perfectly!

**Comment by hez2010** [comment]
It has been fixed in the main branch by https://github.com/Clancey/vscode-comet/pull/15.
But the version containing the fix hasn't been released yet.

@Clancey Can you publish a new release on the vscode extension marketplace? Otherwise users cannot use comet on vscode for Android at all when they're building apps against API level 31+.

**Comment by Clancey** [comment]
Just told CI to push a new version

**Comment by JaneySprings** [comment]
It looks like nothing has changed, but thanks for the answer!
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/48021947/156134335-73de543f-2d86-42c9-ab54-5332365a41dd.png">

**Comment by hez2010** [comment]
Can you try calling mobile-debug manually and see the inner exception?

**Comment by hez2010** [comment]
```
cd ~/.vscode\extensions\clancey.comet-debug-0.3.16\src\mobile-debug\bin\Debug\net6.0
dotnet .\mobile-debug.dll util -c=devices
```

**Comment by JaneySprings** [comment]
> Can you try calling mobile-debug manually and see the inner exception?
Output:
{"id":"25b133b5-720e-4087-a988-b434f9b4071d","command":"devices","error":"The given key 'tag.display' was not present in the dictionary."}

**Comment by hez2010** [comment]
It turns out to be no `tag.diaply` in your avd config.ini. I've sent a PR #18 to fix this.
To workaround this issue, you may add a dummy config in your avd `config.ini`:

```ini
tag.display=Default
tag.id=default
```

**Comment by JaneySprings** [comment]
Thank you so much, it works!
<img width="643" alt="image" src="https://user-images.githubusercontent.com/48021947/156155974-1220d0ec-4be9-4754-91fe-cf0ac1f1f3c1.png">
