### ISSUE TITLE
Loading at `Looking for Mobile .NET Projects loaded via OmniSharp`

### ISSUE THREAD

**Issue by yunusefendi52** [Clancey/vscode-comet#33]
Tried vsix from this commit https://github.com/Clancey/vscode-comet/commit/f7c19f735ad7952a337f9ec2906d65f4d26cdb37 stuck at the `Looking for mobile ...`, I think it's a packaging issue because DotNetWorkspaceAnalyzer didn't included in vsix? I repackaged the vsix to include DotNetWorkspaceAnalyzer build and it's now working

**Comment by Redth** [comment]
Finally should be fixed in 0.7.0 - just need to get this up to marketplace now.
